name: audacity
adopt-info: audacity
description: |
  Audacity® is a free, easy-to-use, multi-track audio editor and recorder for Windows,
  Mac OS X, GNU/Linux and other operating systems. The interface is translated into
  many languages.

  You can use Audacity to:
  * Record live audio
  * Convert tapes and records into digital recordings or CDs
  * Edit WAV, AIFF, FLAC, MP2, MP3 or Ogg Vorbis sound files
  * Cut, copy, splice or mix sounds together
  * Change the speed or pitch of a recording
  * Apply a wide range of other effects to audio recordings

grade: stable
confinement: strict
base: core18
compression: lzo

architectures:
  - build-on: amd64
  - build-on: i386

layout:
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/audacity:
    bind: $SNAP/usr/share/audacity
  /usr/share/locale:
    bind: $SNAP/usr/share/locale

plugs:
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes:gtk-2-engines
  gtk-2-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-2-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sound-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes

environment:
  FINAL_BINARY: $SNAP/usr/bin/audacity
  GTK_PATH: $SNAP/lib/gtk-2.0
  LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  XDG_DATA_DIRS: $SNAP/data-dir:$SNAP/usr/share:$XDG_DATA_DIRS

apps:
  audacity:
    command: bin/check-ld-cache $SNAP/usr/bin/audacity
    # extensions: [gnome-3-28]
    command-chain:
    - bin/desktop-launch
    - snap/command-chain/alsa-launch
    desktop: usr/share/applications/audacity.desktop
    common-id: org.audacityteam.Audacity
    plugs:
      - alsa
      - audio-playback
      - audio-record
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - jack1
      - network
      - network-bind
      - pulseaudio
      - removable-media
      - unity7
      - wayland
      - x11

parts:
  fix-symlinks:
    # REF: https://unix.stackexchange.com/questions/100918/convert-absolute-symlink-to-relative-symlink-with-simple-linux-command
    plugin: nil
    override-build: |
      cat <<'EOF' > $SNAPCRAFT_PART_INSTALL/fix-symlinks.sh
      cd $SNAPCRAFT_PART_INSTALL
      find . -lname '/*' | while read l ; do
        echo ln -sf $(echo $(echo $l | sed 's|/[^/]*|/..|g')$(readlink $l) | sed 's/.....//') $l
      done | sh
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/fix-symlinks.sh
    prime:
      - -*

  scripts:
    source: scripts
    plugin: dump
    organize:
      build-ld-cache: bin/build-ld-cache
      check-ld-cache: bin/check-ld-cache

  desktop-gtk2:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk2"]
    build-packages:
      - libgtk2.0-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libatk-adaptor
      - libcanberra-gtk-module
      - libgail-common
      - libgtk2.0-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk2.0-bin
      - unity-gtk2-module
      - libappindicator1
      - locales-all
      - ibus-gtk
      - libibus-1.0-5

  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad

  wxwidgets:
    after: [desktop-gtk2]
    source: https://github.com/audacity/wxWidgets.git
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --with-gtk
      - --enable-html
      - --enable-intl
      - --enable-xlocale
      - --enable-sockets
      - --enable-debugreport
    override-build: |
      snapcraftctl build
      rm $SNAPCRAFT_PART_INSTALL/usr/bin/wx-config
      ln -s ../lib/wx/config/gtk2-unicode-3.1 $SNAPCRAFT_PART_INSTALL/usr/bin/wx-config
      sed -E -i 's|^prefix=(.*)-/usr|prefix=\1-'"$SNAPCRAFT_STAGE"'/usr|' $SNAPCRAFT_PART_INSTALL/usr/bin/wx-config
    build-environment:
      - CFLAGS: -O2 -pipe
      - CXXFLAGS: -O2 -pipe
    build-packages:
      - g++
      - libglu1-mesa-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer1.0-dev
      - libgtk2.0-dev
      - libjpeg8-dev
      - liblzma-dev
      - libmspack-dev
      - libnotify-dev
      - libsdl2-dev
      - libsecret-1-dev
      - libsoup2.4-dev
      - libtiff-dev
      - nasm
    stage-packages:
      - libglu1-mesa
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - libgtk2.0-0
      - libice6
      - libjpeg8
      - liblzma5
      - libmspack0
      - libnotify4
      - libsdl2-2.0-0
      - libsecret-1-0
      - libsm6
      - libsoup2.4-1
      - libtiff5

  audacity:
    after: [alsa-mixin, desktop-gtk2, wxwidgets]
    plugin: cmake
    source: https://github.com/audacity/audacity.git
    parse-info: [usr/share/appdata/audacity.appdata.xml]
    override-pull: |
      snapcraftctl pull
      last_committed_tag="$(git describe --tags --abbrev=0)"
      last_released_tag="$(snap info $SNAPCRAFT_PROJECT_NAME | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
        snapcraftctl set-version "$(echo "${last_committed_tag}" | sed -E -e "s|^$SNAPCRAFT_PROJECT_NAME-?||i")"
      else
        snapcraftctl set-version "$(git rev-parse --short HEAD)"
      fi
      sed -i -E 's|Icon=.*|Icon=/usr/share/icons/hicolor/scalable/apps/audacity.svg|' src/audacity.desktop.in
      sed -i -E 's|Exec=env UBUNTU_MENUPROXY=0 |Exec=|' src/audacity.desktop.in
      git show -s --format="#define REV_LONG \"%H\"%n#define REV_TIME \"%cd\"%n" | tee src/RevisionIdent.h
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/snap/audacity/current/usr
      - -DCMAKE_BUILD_TYPE=Release
    build-snaps:
      - cmake
    build-environment:
      - PATH: /snap/bin:$PATH
      - CFLAGS: -O2 -pipe
      - CXXFLAGS: -O2 -pipe
      - WX_CONFIG: $SNAPCRAFT_STAGE/usr/bin/wx-config
    build-packages:
      - gettext
      - libavformat-dev
      - libflac-dev
      - libflac++-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libgstreamer1.0-dev
      - libgtk2.0-dev
      - libid3tag0-dev
      - libjack-jackd2-dev
      - libmad0-dev
      - libmp3lame-dev
      - libogg-dev
      - libportmidi-dev
      - libportsmf-dev
      - libpulse-dev
      - libsbsms-dev
      - libsndfile1-dev
      - libsoundtouch-dev
      - libsoxr-dev
      - libtwolame-dev
      - libvamp-hostsdk3v5
      - libvorbis-dev
      - python
      - python3
    stage-packages:
      - appmenu-gtk2-module
      - libavformat57
      - libflac++6v5
      - libflac8
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libgstreamer1.0-0
      - libgtk2.0-0
      - libid3tag0
      - libmad0
      - libmp3lame0
      - libogg0
      - libportmidi0
      - libportsmf0v5
      - libpulse0
      - libsbsms10
      - libsndfile1
      - libsoundtouch1
      - libsoxr0
      - libtwolame0
      - libvamp-hostsdk3v5
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - nasm
    organize:
      snap/audacity/current/usr: usr
    prime:
      - -snap/audacity

  gtk-locales:
    plugin: nil
    build-packages:
    - apt
    - dpkg
    override-pull: |
      set -eux
      apt download "language-pack-gnome-*-base"
    override-build: |
      set -eux
      for deb in *.deb; do dpkg-deb -x $deb .; done
      find usr/share/locale-langpack -type f -not -name "gtk20*.mo" -exec rm '{}' \;
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share
      cp -R usr/share/locale-langpack $SNAPCRAFT_PART_INSTALL/usr/share/

  # Ship a default set of GSettings schemas so that the correct theme is used
  # in Wayland sessions on Ubuntu (see https://forum.snapcraft.io/t/7806/3).
  desktop-settings-packages:
    after: [ desktop-gtk2 ]
    plugin: nil
    build-packages:
    - libglib2.0-bin
    stage-packages:
    - gsettings-desktop-schemas
    - ubuntu-settings
    prime:
    - usr/share/glib-2.0/schemas/*

  desktop-settings-build:
    plugin: nil
    after: [ audacity, desktop-settings-packages ]
    override-prime: |
      set -eux
      glib-compile-schemas usr/share/glib-2.0/schemas

  cleanup:
    after: [ audacity, desktop-settings-build ]
    plugin: nil
    build-snaps:
    - core18
    - gtk-common-themes
    - gtk2-common-themes
    override-prime: |
      set -eux
      cd /snap/gtk-common-themes/current
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/{} \;
      cd /snap/gtk2-common-themes/current/lib
      find . -type f,l -exec rm -f $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/{} \;
